python3 -m benchmarker \
    --framework=pytorch \
    --backend=native \
    --problem=deepcam \
    --cnt_samples_per_epoch=64 \
    --sample_shape=3,512,512 \
    --batch_size=32 \
    --mode=inference \
    --preheat \
    --nb_epoch=10 \
    --precision=FP16 \
    --gpus=0 \
    --power_nvml
