python3 -m benchmarker \
    --framework=pytorch \
    --backend=native \
    --problem=deepcam \
    --problem_size=640,3,512,512 \
    --batch_size=32 \
    --mode=inference \
    --preheat \
    --nb_epoch=10 \
    --precision=FP16 \
    --gpus=0 \
    --power_nvml
